### ISSUE TITLE
private function currentMaps() to public

### ISSUE THREAD

**Issue by remrem** [Deutsche-Squad-Gemeinschaft/squad-rcon-php#6]
Hi !
Can you modify in SquadServer.php `private function currentMaps()` to `public function currentMaps()` ?

P.S. thanks for this useful library ;)
P.S. sorry for my bad english :/

**Comment by bumbummen99** [comment]
Hey, sorry i totally did not see this issue >.>

I think with the current v2 refactor this should be solved anyways 👍
